@startuml trino-bios-design
title Isima bi(OS) plugin for Trino - class design

left to right direction
skinparam shadowing false

skinparam class {
    BackgroundColor<<Trino>> white
    BorderColor<<Trino>> gray
    BackgroundColor<<Major>> moccasin
    FontSize<<Major>> 15
}

class BiosConfig << (P, orange) >> {
    + URI url
    + String email
    + String password
    + Long defaultTimerangeDeltaSeconds
}

class BiosClient <<Major>> {
    # @Inject Cons (BiosConfig, ...)
    - biosConfig
    - session
    + getSchemaNames ()
    + getTableNames (String schema)
    + BiosTable getTable (schema, tableName)
}

interface ColumnHandle <<Trino>> {
    + hashCode ()
    + equals (Object)
}

class BiosColumnHandle << (J, orangeRed) >> implements ColumnHandle {
    + Cons (...)
    - String columnName
    - Type columnType
    - String defaultValue
    - boolean isKey
    - boolean isRecordTimestamp
    + getColumnMetadata ()
}

interface Connector <<Trino>> {
    beginTransaction ()
    getMetadata ()
    getSplitManager ()
    getRecordSetProvider ()
    shutdown ()
}

class BiosConnector implements Connector {
    # @Inject Cons (...)
}

interface ConnectorFactory <<Trino>> {
    getName ()
    create (catalogName, config, context)
}

class BiosConnectorFactory implements ConnectorFactory {
}

interface ConnectorMetadata <<Trino>> {
    listSchemaNames ()
    getTableHandle ()
    getTableMetadata ()
    listTables ()
    getColumnHandles ()
    listTableColumns ()
    getColumnMetadata ()
    getTableProperties ()
}

class BiosMetadata <<Major>> implements ConnectorMetadata {
    # @Inject Cons (biosClient)
    - getTableMetadata (schemaTableName)
    - listTables (session, prefix)
}

interface Module <<Trino>> {
  configure (binder)
}

class BiosModule implements Module {
}

interface Plugin <<Trino>> {
    getConnectorFactories()
}

class BiosPlugin implements Plugin {
}

interface RecordCursor <<Trino>> {
    getType (int field)
    getBoolean (int field)
    get... (int field)
    isNull (int field)
    advanceNextPosition ()
    close ()
    getCompletedBytes ()
    getReadTimeNanos ()
}

class BiosRecordCursor <<Major>> implements RecordCursor {
    + Cons (client, statement, columnHandles)
    - biosclient
    - statement
    - columnHandles
    - records
    - currentRecord
}

interface RecordSet <<Trino>> {
    getColumnTypes ()
    cursor ()
}

class BiosRecordSet implements RecordSet {
    + Cons (biosSplit, columnHandles)
}

interface ConnectorRecordSetProvider <<Trino>> {
    getRecordSet (transaction, session, split, table, columns)
}

class BiosRecordSetProvider implements ConnectorRecordSetProvider {
}

interface ConnectorSplit <<Trino>> {
    isRemotelyAccessible ()
    getAddresses ()
    getInfo ()
}

class BiosSplit implements ConnectorSplit {
    + Cons (tableName)
    + getTableName ()
}

interface ConnectorSplitManager <<Trino>> {
    getSplits ()
}

class BiosSplitManager implements ConnectorSplitManager {
    # @Inject Cons (biosClient)
}

enum BiosTableKind {
    SIGNAL
    CONTEXT
}

class BiosTable << (P, orange) >> {
    + Cons (...)
    - tableHandle
    - columns
}

interface ConnectorTableHandle <<Trino>>

class BiosTableHandle << (J, orangeRed) >> implements ConnectorTableHandle {
    + Cons (...)
    - String schemaName
    - String tableName
    - Long timeRangeStart
    - Long timeRangeDelta
    + toSchemaTableName ()
}

interface ConnectorTransactionHandle <<Trino>>

class BiosTransactionHandle implements ConnectorTransactionHandle {
    + INSTANCE
}

class ConnectorTableMetadata << (P, orange) >> <<Trino>> {
    - SchemaTableName
    - List<ColumnMetadata>
    - properties
    - comment
}


entity Process_Initialization <<Trino>>
Process_Initialization --> Module
Process_Initialization --> Plugin
Process_Initialization --> ConnectorFactory
Process_Initialization --> BiosClient
Process_Initialization --> BiosMetadata
Process_Initialization --> BiosSplitManager
Process_Initialization --> BiosConnector
BiosConnectorFactory ..> BiosConfig
BiosClient ..> BiosConfig

entity Show_Schemas <<Trino>>
Show_Schemas --> Connector
Show_Schemas --> ConnectorMetadata
'BiosMetadata ..> BiosClient
'BiosSplitManager ..> BiosClient
'BiosRecordCursor ..> BiosClient
'BiosRecordSet ..> BiosClient
'BiosRecordSetProvider ..> BiosClient
BiosClient ..> BiosTable
BiosTable ..> BiosTableKind
BiosTable ..> BiosTableHandle
BiosTable ..> BiosColumnHandle

entity Show_Tables <<Trino>>
Show_Tables --> ConnectorMetadata

entity StartSelect <<Trino>>
StartSelect --> ConnectorMetadata
StartSelect --> ConnectorTransactionHandle
StartSelect --> ConnectorTableHandle
StartSelect --> ColumnHandle
StartSelect --> ConnectorSplitManager
StartSelect --> ConnectorSplit
StartSelect --> ConnectorRecordSetProvider
StartSelect --> RecordSet
BiosMetadata ..> ConnectorTableMetadata

entity RetrieveData <<Trino>>
RetrieveData --> RecordCursor


Process_Initialization .[hidden]> Show_Schemas
Show_Schemas .[hidden]> Show_Tables
Show_Tables .[hidden]> StartSelect
StartSelect .[hidden]> RetrieveData

BiosModule .[hidden]> BiosPlugin
BiosPlugin .[hidden]> BiosConnectorFactory
BiosConnectorFactory .[hidden]> BiosClient

BiosClient .[hidden]> BiosMetadata
BiosMetadata .[hidden]> BiosSplitManager
BiosSplitManager .[hidden]> BiosConnector


ConnectorMetadata .[hidden]> ConnectorTransactionHandle
ConnectorTransactionHandle .[hidden]> ConnectorTableHandle
ConnectorTableHandle .[hidden]> ColumnHandle
ColumnHandle .[hidden]> ConnectorSplitManager
ConnectorSplitManager .[hidden]> ConnectorSplit
ConnectorSplit .[hidden]> ConnectorRecordSetProvider
ConnectorRecordSetProvider .[hidden]> RecordSet



newpage
title Legend

interface Interface1 {
    + function1() - implemented by Bios class
}

class Class implements Interface1 {
    + Cons () - Constructor
    - privateVariable
    + publicVariable
    - privateFunction()
    + publicFunction()
}

class POJO << (P, orange) >> {
    + Cons () - Constructor
    - gettable member
    + gettable and settable member
}

class JsonPOJO << (J, orangeRed) >> {
    + Cons () - Constructor
    - gettable member
    + gettable and settable member
}

@enduml
